name: Release

permissions:
  contents: write

on:
  push: { tags: ["*"] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with: { php-version: "8.3", tools: box }
      - run: composer install
      - run: bin/release "${GITHUB_REF#refs/tags/}"
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.phar
            dist/*.tar.gz
            dist/*.zip
