name: Tests

on:
  push: { branches: ["*"] }

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      wiremock:
        image: wiremock/wiremock:3.10.0
        ports: ["8080:8080"]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with: { php-version: "8.3" }
      - run: composer validate
      - run: composer install --prefer-dist --optimize-autoloader
      - run: vendor/bin/phpstan --no-progress
      - run: vendor/bin/php-cs-fixer check --show-progress=none
      - run: npx prettier --check .
      - run: vendor/bin/phpunit --coverage-clover coverage.xml
      - uses: coverallsapp/github-action@v2
